# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /
title: Marc S
author: Marc S
description: Personal blog and resume
avatar: profile.png
email: yourname@email.com
github: kruid # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
title: TEST - Kruid


# needed for travis-ci build
exclude: [vendor]
